name: Nepremicnine.net Scraper

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Omogoči ročni zagon v GitHub zavihku "Actions"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install chromium --with-deps

      - name: Run Scraper
        run: bun index.ts 
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}