name: Nepremicnine.net Scraper

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install chromium --with-deps

      - name: Run Scraper
        run: bun index.ts 
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}

      - name: Upload Debug Screenshot
        if: failure() # To se sproži samo, če "Run Scraper" javi napako
        uses: actions/upload-artifact@v4
        with:
          name: scraper-error-screenshot
          path: error-debug.png # Prepričaj se, da v index.ts shraniš sliko pod tem imenom!
          retention-days: 3